### ISSUE TITLE
[Bug]Next Aired

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon#302] opened 2020-10-24 04:49 UTC
v0.5.49
After updating AH, Next Aired has stopped working. 
![blank](https://user-images.githubusercontent.com/2873112/97068132-aa4add00-15bc-11eb-9f31-46ca9d18cc44.jpg)

**Comment by jurialmunkey** [comment] 2020-10-26 12:27
Ah it'll be related to the recent TMDbHelper updates. I'll try and get a fix out ASAP.

**Comment by jurialmunkey** [comment] 2020-10-26 12:34
Actually is it still not working for you because it's working for me now? Maybe Trakt was down at the time.

![Honeyview_screenshot276](https://user-images.githubusercontent.com/4618719/97172890-d005fb00-17e3-11eb-96f7-5267c95f8997.jpg)

**Comment by jurialmunkey** [comment] 2020-10-26 12:45
Ah I think I see what the issue is - if you haven't authorized a Trakt account it won't work but shouldn't need auth to grab the calendar. I just need to remove the auth check from that function.

@Blurayx - Can you try latest  version of TMDbHelper from github - I think it should be fixed now.
https://github.com/jurialmunkey/plugin.video.themoviedb.helper

**Comment by Blurayx** [comment] 2020-10-26 13:50
it's working but the fanarts are either blank or doesn't match my Tv shows library.
Next Aired
![Next Aired](https://user-images.githubusercontent.com/2873112/97180207-ac19c980-1791-11eb-8345-6f14eefe90ae.jpg)
Library
![library ](https://user-images.githubusercontent.com/2873112/97180250-b9cf4f00-1791-11eb-8094-ed404a57995b.jpg)
Settings
![settings](https://user-images.githubusercontent.com/2873112/97180559-21859a00-1792-11eb-86e1-0363a3552fbf.jpg)

Thanks

**Comment by Blurayx** [comment] 2020-10-28 02:26
Fixed😀

Thank you so much, I relie on Next Aired everyday.
![screenshot002](https://user-images.githubusercontent.com/2873112/97383049-9d7fff00-18c4-11eb-9b26-8a6400bc9e9d.png)

**Comment by jurialmunkey** [comment] 2020-10-29 14:54
Ah so it works for the ones missing thumbs too? That's great news!

Thanks so much for testing and your patience while I figured this one out! 😁

**Closed by jurialmunkey** 2020-10-29 14:54 UTC
