### ISSUE TITLE
[Bug] Selecting a Kodi Favorite Item crashes Kodi

### ISSUE THREAD

**Issue by Goldsucher** [jurialmunkey/skin.arctic.horizon#38] opened 2020-03-20 12:53 UTC
When you click on a favorites item, Kodi is crashing. 

Device is Nvidia SHIELD/Android - Kodi 18.6

**Comment by alKODIque** [comment] 2020-03-20 17:03
Same issue

**Comment by jurialmunkey** [comment] 2020-03-20 23:23
I can reproduce this issue. I just have no idea what is causing it though. 

It's not something in the favourites dialog because I tried replacing it with a very basic version and it still crashes. 

I'm looking into it but I really don't have any idea what is causing it.

**Comment by jurialmunkey** [comment] 2020-03-21 02:39
This bug appears to be due an issue in Kodi core. A workaround has been applied so it should be fixed in the skin now. Massive thanks to Ronie for finding the workaround
https://forum.kodi.tv/showthread.php?tid=352715&pid=2933054#pid2933054

Ronie's PR to fix the bug in Kodi core: https://github.com/xbmc/xbmc/pull/17528

---
Relevant Commit: https://github.com/jurialmunkey/skin.arctic.horizon/commit/caa4da73769318094f815003d8411aa27502082b

**Comment by alKODIque** [comment] 2020-03-21 02:49
thanks a lot for sharing the info

**Closed** 2020-03-21 03:09 UTC
Labels: help wanted
