### ISSUE TITLE
[Bug] [Matrix] Versions function not working

### ISSUE THREAD

**Issue by tbmmbt** [jurialmunkey/skin.arctic.horizon#373] opened 2021-03-08 10:07 UTC
I've switched to this skin after the Matrix update and it's really great but one thing that doesn't seem to be working for me is the 'Versions' option for any add-on. When I select 'Versions' it just jumps back to the menu and does nothing. I've tried switching back to Estuary and it works fine there. Is this something specific to my install or is the Versions option not working?

**Comment by peat80** [comment] 2021-03-08 12:33
Was fixed yesterday in latest matrix build. Install latest build from github or wait till the repo was updated. 😀

**Comment by jurialmunkey** [comment] 2021-03-08 21:32
Duplicate of https://github.com/jurialmunkey/skin.arctic.horizon/issues/371

As mentioned above, already fixed on latest git version.

**Closed as completed by jurialmunkey** 2021-03-08 21:32 UTC
