### ISSUE TITLE
Script.skinvariables error

### ISSUE THREAD

**Issue by Jackp7173** [jurialmunkey/skin.arctic.horizon#377] opened 2021-03-11 14:23 UTC
I have updated the skin variables addon to 0.0.3 however i continually get a skin variables error code and then 'constructing variables' stuck at 0% ???

**Comment by drinfernoo** [comment] 2021-03-11 16:33
Duplicate of #374.

**Comment by jurialmunkey** [comment] 2021-03-12 05:06
Skin requires v0.2.3 of skin variables.

**Closed as completed by jurialmunkey** 2021-03-12 05:06 UTC
