### ISSUE TITLE
[Bug]   Crashing after Installing AH

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon#249] opened 2020-08-23 08:41 UTC
When installing AH, Kodi crashes but after reopening Kodi, AH updates as normal.
I have noticed this issue with all the updates this week. This happens on the iMac & Nvidia TV

Reopening Kodi after crash
<img width="1462" alt="Screenshot 2020-08-23 at 09 31 26" src="https://user-images.githubusercontent.com/2873112/90974598-ac44e100-e524-11ea-9c03-984227048099.png">

**Comment by jurialmunkey** [comment] 2020-08-25 03:34
Can you test installing latest version (v0.5.4)? I'm fairly certain I've located the cause of the crash and hopefully should be fixed now.

**Comment by Blurayx** [comment] 2020-08-25 04:00
I can confirm installation crash issue solved.  Tested on my iMac & Nvidia Shield TV  
![default_thumbsup_anim](https://user-images.githubusercontent.com/2873112/91121503-d830a580-e68f-11ea-8c8c-14bc0f7d9aa3.gif)

**Closed** 2020-08-25 04:19 UTC
