### ISSUE TITLE
Widget-Autoscrolling for Banner + Fullscreen-Widget not working

### ISSUE THREAD

**Issue by Goldsucher** [jurialmunkey/skin.arctic.horizon#179] opened 2020-05-23 23:29 UTC
I mentioned this already in the forum:

The autoscrolling for fullscreen widget isn't working and I also noticed, that banners also don't autoscroll anymore (don't know exactly since when, but maybe since 2 weeks?)

Device is Shield/Android.

**Comment by jurialmunkey** [comment] 2020-05-24 00:48
Duplicate of this issue: https://github.com/jurialmunkey/skin.arctic.horizon/issues/148

**Comment by jurialmunkey** [comment] 2020-05-24 00:49
Not sure why banner has stopped. I'll look into these auto scroll issues soon.

**Closed by jurialmunkey** 2020-05-24 00:48 UTC

**Comment by jurialmunkey** [comment] 2020-05-30 04:20
@Goldsucher - Actually just realised that this is a separate issue. 

Do you use Profiles by any chance, or have you changed the language since setting the autoscroll interval value?

The autoscroll is based upon a skin string - so if you change languages, it will no longer match. And there is currently a Kodi bug where if you're using profiles, skin strings don't load properly sometimes.

**Comment by Goldsucher** [comment] 2020-05-31 18:57
@jurialmunkey 

thanks for the investigation. I am not using profiles and didn't changed the language. Autoscrolling still doesn't work for me with latest version

**Comment by jurialmunkey** [comment] 2020-05-31 23:39
This is so weird. It is working fine for me. Are you sure you have autoscroll widgets turned on in home settings and an autoscroll value set in background settings? (also maybe try setting a value again).

**Comment by jurialmunkey** [comment] 2020-05-31 23:41
Also note that it will only autoscroll if unfocused and system is idle (ie no button presses)

**Comment by Goldsucher** [comment] 2020-05-31 23:47
uhm sorry maybe I misunderstood you.

If I enable it, autoscrolling is working, but I thought, banners and fullscreen-widgets always autoscroll nevertheless if it's enabled oder disabled?

**Comment by drinfernoo** [comment] 2020-06-01 00:55
So it's working when enabled, but the setting value doesn't change the behavior for you?

**Comment by jurialmunkey** [comment] 2020-06-01 01:00
> If I enable it, autoscrolling is working, but I thought, banners and fullscreen-widgets always autoscroll nevertheless if it's enabled or disabled?

In AZ2 it worked like that -- option only enabled/disabled scrolling for single widgets, but banners auto scrolled. However, some users were complaining about the autoscroll on banners, so I made it a blanket rule in AH that covers banners, fullscreen/showcase widgets, and also single widgets -- I thought it would be excessive to have individual settings for each.

**Comment by Goldsucher** [comment] 2020-06-01 01:07
> > If I enable it, autoscrolling is working, but I thought, banners and fullscreen-widgets always autoscroll nevertheless if it's enabled or disabled?
> 
> In AZ2 it worked like that -- option only enabled/disabled scrolling for single widgets, but banners auto scrolled. However, some users were complaining about the autoscroll on banners, so I made it a blanket rule in AH that covers banners, fullscreen/showcase widgets, and also single widgets -- I thought it would be excessive to have individual settings for each.

okay that explains it.
So the behaviour should be:
autoscrolling on: banners, fullscreen widgets & single widgets scroll
autoscrolling off: NO widget scroll

If that's the case, everything works like it should be.

**Comment by jurialmunkey** [comment] 2020-06-01 04:06
Yep, that's correct!
