### ISSUE TITLE
[Bug] overview & options

### ISSUE THREAD

**Issue by Blurayx** [jurialmunkey/skin.arctic.horizon#16] opened 2020-03-18 01:10 UTC
Nothing happens when I click on overview or options

<a href="https://imgur.com/4hmeSo3"><img src="https://i.imgur.com/4hmeSo3.png" title="source: imgur.com" /></a>

**Comment by jurialmunkey** [comment] 2020-03-18 01:51
Duplicate of this issue: https://github.com/jurialmunkey/skin.arctic.horizon/issues/10

**Closed by jurialmunkey** 2020-03-18 01:51 UTC

**Comment by jurialmunkey** [comment] 2020-03-18 03:09
Fixed in v0.1.10 - https://github.com/jurialmunkey/skin.arctic.horizon/commit/27ab0d933c57ef4fb639ebd5673adcf09fa41b5b
